config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :bootsts do 
    collection do

      get :home
      get :singup
      get :singin
    end
  end
    # get 'home'=> 'bootsts#home'
    # get 'singup' => 'bootsts#singup'
    # get 'singin' => 'bootsts#singin'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bootsts_controller.rb
class BootstsController < ApplicationController
    def home 
    end

    def singup
    end

    def singin
    end
    
    def create
    end

    def new
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootst_helper.rb
module BootstHelper
end

app/views/bootsts/home.html.erb
<%= render 'layouts/header' %>
<%= render 'layouts/trydemo' %>

app/views/bootsts/singin.html.erb
<%= render 'layouts/header' %>
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<body>
<div class="container">
  <div class="jumbotron">
  <h1> login </h1>
  <%= form_with scope: :bootsts, url: new_bootst_path , local: true do |f| %>
    

  <div class="form-group">
  <div class="control-label col-md-2">
    <%= f.label :username %>
  </div>
  <div class="col-sm-10">     
   <%= f.text_field :username,placeholder:"username",class:"form-control" %>
  </div>
</div>
<br>
<br>
<br> 

<div class="form-group">
  <div class="control-label col-sm-2">
      <%= f.label :password%>
  </div>
  <div class="col-sm-10">     
      <%= f.text_field :password,placeholder:"password",class:"form-control" %>
  </div>
</div>
<br>
<br>
<br>


<div class="form-group">
  <div class="control-label col-sm-offset-5 col-sm-2">
  <%= f.submit "Singup", class: "btn-size" %>
  </div>    
</div>
  
<% end %>


</div>     
</div>

​

</body>
</html>

​

app/views/bootsts/singup.html.erb
<%= render 'layouts/header' %>
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<body>

<div class="container">
  <div class="jumbotron">
  <h1> register </h1>

    <%= form_with scope: :bootsts, url: bootsts_path , local: true do |f| %>
   
    <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name%>
        </div>
        <div class="col-sm-10">     
         <%= f.text_field :name,placeholder:"name",class:"form-control" %>
        </div>
    </div>
  <br>
  <br>
  <br> 

    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :username%>
        </div>
        <div class="col-sm-10">     
            <%= f.text_field :username,placeholder:"username",class:"form-control" %>
        </div>
    </div>
    <br>
    <br>
    <br>

    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :password%>
        </div>
        <div class="col-sm-10">     
            <%= f.text_field :password,placeholder:"password",class:"form-control" %>
        </div>
    </div>

    <br>
    <br>
    <br>

    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :confimpassword%>
        </div>
        <div class="col-sm-10">     
            <%= f.text_field :confimpassword,placeholder:"confimpassword",class:"form-control" %>
        </div>
    </div>

    <br>
    <br>
    <br>

    <div class="form-group">
        <div class="control-label col-sm-offset-5 col-sm-2">
        <%= f.submit "Singup", class: "btn-size" %>
        </div>    
    </div>
        
    <% end %>


</div>     
</div>


</body>
</html>

​

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<title>Bootstrap Example</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
<div class="container-fluid">
  <div class="navbar-header">
    <a class="navbar-brand" href="#">WebSiteName</a>
  </div>
  
  <ul class="nav navbar-nav"> 
    
  </ul>
 
  <ul class="nav navbar-nav navbar-right">
    <li><a href="/bootsts/home">Home</a></li>
    <li><a href="#">About Us</a></li>
    <li><a href="#">Contact Us</a></li>
    <li><a href="/bootsts/singup"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
    <li><a href="/bootsts/singin"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
  </ul>
  </div>
</div>
</nav> 
</body>
</html> 

app/views/layouts/_trydemo.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Theme Made By www.w3schools.com - No Copyright -->
  <title>Bootstrap Theme The Band</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <style>


  

  .img-circle {
    border-radius: 50%;
  }

  .container {
    padding: 80px 120px;
  }
  .person {
    border-radius: 50%;
   
    margin-bottom: 25px;
    width: 80%;
    height: 80%;
    opacity: 0.7;
  }
  .person:hover {
    border: 10px solid transparent;
    border-color: #f1f1f1;
  }
  .carousel-inner img {
    -webkit-filter: grayscale(90%);
    filter: grayscale(90%); /* make all photos black and white */ 
    width: 100%; /* Set width to 100% */
    margin: auto;
  }
  .carousel-caption h3 {
    color: #fff !important;
  }
  @media (max-width: 600px) {
    .carousel-caption {
      display: none; /* Hide the carousel text when the screen is less than 600 pixels wide */
    }
  }  
  </style>
</head>
<body>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
      <%= link_to image_tag('imag.jpeg') %>
        <div class="carousel-caption">
          <h3>New York</h3>
          <p>The atmosphere in New York is lorem ipsum.</p>
        </div>      
      </div>

      <div class="item">
      <%= link_to image_tag('imag.jpeg') %>
        <div class="carousel-caption">
          <h3>Chicago</h3>
          <p>Thank you, Chicago - A night we wont forget.</p>
        </div>      
      </div>
    
      <div class="item">
      <%= link_to image_tag('imag.jpeg') %>
        <div class="carousel-caption">
          <h3>LA</h3>
          <p>Even though the traffic was a mess, we had the best time playing at Venice Beach!</p>
        </div>      
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>


#circle image

<div class="container text-center">
  <h3>THE BAND</h3>
  <p><em>We love music!</em></p>
  <p>We have created a fictional band website. Lorem ipsum..</p>
  <br>
  <div class="row">
    <div class="col-sm-4">
      <p class="text-center"><strong>Name</strong></p><br>
      <a href="#demo" data-toggle="collapse">
      
        <%# img src="bandmember.jpg" class="img-circle person" alt="Random Name" width="255" height="255"%>
        <%= link_to image_tag('imag.jpeg'), class: "img-circle person" %>
      </a>

      <div id="demo" class="collapse">
        <p>Guitarist and Lead Vocalist</p>
        <p>Loves long walks on the beach</p>
        <p>Member since 1988</p>
      </div>
    </div>
    <div class="col-sm-4">
      <p class="text-center"><strong>Name</strong></p><br>
      <a href="#demo2" data-toggle="collapse">
        <%#img src="bandmember.jpg" class="img-circle person" alt="Random Name" width="255" height="255"%>
        <%= link_to image_tag('imag.jpeg') %>
      </a>
      <div id="demo2" class="collapse">
        <p>Drummer</p>
        <p>Loves drummin'</p>
        <p>Member since 1988</p>
      </div>
    </div>
    <div class="col-sm-4">
      <p class="text-center"><strong>Name</strong></p><br>
      <a href="#demo3" data-toggle="collapse">
        <%#img src="bandmember.jpg" class="img-circle person" alt="Random Name" width="255" height="255"%>
        <%= link_to image_tag('imag.jpeg') %>
      </a>
      <div id="demo3" class="collapse">
        <p>Bass player</p>
        <p>Loves math</p>
        <p>Member since 2005</p>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BootDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>